
name: Dependabot auto-merge (minor & patch only if CI passes)

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Wait for CI checks
        uses: actions/github-script@v7
        with:
          script: |
            const { data: checks } = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha
            })

            const allChecksPassed = checks.check_runs.every(c => c.conclusion === "success")
            if (!allChecksPassed) {
              core.setFailed("Not all CI checks passed.")
            }

      - name: Check PR labels
        id: check-labels
        run: |
          echo "labels=$(jq -r '.pull_request.labels[].name' $GITHUB_EVENT_PATH || true)" >> $GITHUB_ENV

      - name: Auto-merge Dependabot PR (minor/patch only)
        if: contains(env.labels, 'dependencies') && !contains(env.labels, 'major')
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: "squash"
            })
