name: Dependabot auto-merge

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
      - name: Check PR labels
        run: |
          echo "Labels: ${{ toJSON(github.event.pull_request.labels) }}"
          for label in "${{ github.event.pull_request.labels[*].name }}"; do
            if [[ "$label" == "dependencies" ]]; then
              exit 0
            fi
          done
          echo "❌ Pas de label 'dependencies', on ne merge pas."
          exit 1

      - name: Auto-merge Dependabot PR
        if: success() && github.event.pull_request.base.ref == 'main'
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
